version: "3.8"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: hapi
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  hapi-fhir:
    image: hapiproject/hapi:latest
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres:5432/hapi
      - spring.datasource.username=admin
      - spring.datasource.password=secret
      - spring.datasource.driverClassName=org.postgresql.Driver
      - spring.jpa.properties.hibernate.dialect=ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect
      - hapi.fhir.fhir_version=R4
      - hapi.fhir.validation.requests_enabled=false
    depends_on:
      - postgres

  backend:
    build: ../backend
    ports:
      - "8000:8000"
    environment:
      - FHIR_BASE_URL=http://hapi-fhir:8080/fhir
      - AWS_REGION=us-east-1
    depends_on:
      - hapi-fhir

volumes:
  pg-data:
