LABEL_NAMES = [
    'afib_flutter', 'heart_failure', 'hypertension', 'chronic_ihd',
    'acute_mi', 'paroxysmal_tachycardia', 'av_block_lbbb',
    'other_conduction', 'pulmonary_embolism', 'cardiac_arrest',
    'angina', 'pericardial_disease', 'afib_detail', 'hf_detail',
    'dm2', 'acute_kidney_failure', 'hypothyroidism', 'copd',
    'chronic_kidney', 'hyperkalemia', 'hypokalemia',
    'respiratory_failure', 'sepsis', 'calcium_disorder',
]

LABEL_KO = {
    'afib_flutter':           '심방세동/조동',
    'heart_failure':          '심부전',
    'hypertension':           '고혈압',
    'chronic_ihd':            '만성 허혈성 심질환',
    'acute_mi':               '급성 심근경색',
    'paroxysmal_tachycardia': '발작성 빈맥',
    'av_block_lbbb':          '방실차단/좌각차단',
    'other_conduction':       '기타 전도장애',
    'pulmonary_embolism':     '폐색전증',
    'cardiac_arrest':         '심정지',
    'angina':                 '협심증',
    'pericardial_disease':    '심낭질환',
    'afib_detail':            '심방세동(세부)',
    'hf_detail':              '심부전(세부)',
    'dm2':                    '제2형 당뇨병',
    'acute_kidney_failure':   '급성 신부전',
    'hypothyroidism':         '갑상선기능저하증',
    'copd':                   'COPD',
    'chronic_kidney':         '만성 신장질환',
    'hyperkalemia':           '고칼륨혈증',
    'hypokalemia':            '저칼륨혈증',
    'respiratory_failure':    '호흡부전',
    'sepsis':                 '패혈증',
    'calcium_disorder':       '칼슘 대사 이상',
}

LABEL_SEVERITY = {
    'acute_mi':               'critical',
    'cardiac_arrest':         'critical',
    'av_block_lbbb':          'critical',
    'pulmonary_embolism':     'severe',
    'paroxysmal_tachycardia': 'severe',
    'hyperkalemia':           'severe',
    'respiratory_failure':    'severe',
    'sepsis':                 'severe',
    'afib_flutter':           'moderate',
    'heart_failure':          'moderate',
    'afib_detail':            'moderate',
    'hf_detail':              'moderate',
    'angina':                 'moderate',
    'other_conduction':       'moderate',
    'pericardial_disease':    'moderate',
    'hypertension':           'mild',
    'chronic_ihd':            'mild',
    'dm2':                    'mild',
    'acute_kidney_failure':   'mild',
    'hypothyroidism':         'mild',
    'copd':                   'mild',
    'chronic_kidney':         'mild',
    'hypokalemia':            'mild',
    'calcium_disorder':       'mild',
}

LABEL_RECOMMENDATION = {
    'acute_mi':               '즉시 심장내과 협진 및 PCI 팀 호출',
    'cardiac_arrest':         '즉시 CPR 및 제세동 준비',
    'av_block_lbbb':          '즉시 임시 심박동기 삽입 고려',
    'pulmonary_embolism':     'CT 폐혈관조영술(CTPA) 시행',
    'paroxysmal_tachycardia': '미주신경자극 또는 아데노신 투여 고려',
    'hyperkalemia':           '혈액 K+ 즉시 확인, 심전도 모니터링',
    'respiratory_failure':    '산소 공급 및 호흡기 지원',
    'sepsis':                 '혈액배양 후 광범위 항생제 투여',
    'afib_flutter':           '심박수 조절 및 항응고 요법 검토',
    'heart_failure':          'BNP/NT-proBNP 검사 및 이뇨제 투여',
    'afib_detail':            '심박수 조절 및 항응고 요법 검토',
    'hf_detail':              'BNP/NT-proBNP 검사 및 이뇨제 투여',
    'angina':                 '심장내과 협진 및 니트로글리세린 투여',
    'other_conduction':       '지속 심전도 모니터링',
    'pericardial_disease':    '심초음파 시행',
    'hypertension':           '혈압 모니터링 및 항고혈압제 검토',
    'chronic_ihd':            '심장내과 협진',
    'dm2':                    '혈당 확인 및 인슐린 조절',
    'acute_kidney_failure':   '신장내과 협진 및 전해질 모니터링',
    'hypothyroidism':         '갑상선 기능 검사',
    'copd':                   '기관지 확장제 투여',
    'chronic_kidney':         '신장내과 협진',
    'hypokalemia':            '혈액 K+ 확인 및 전해질 보충',
    'calcium_disorder':       '혈중 Ca2+ 확인',
}

# Bedrock Agent가 다음 모달을 호출할 때 사용
NEXT_MODAL_MAP = {
    'acute_mi':           {'modal': 'blood', 'action': '트로포닌 I/T 검사',       'description': '급성 심근경색 의심 — 심근 바이오마커 확인 필요'},
    'heart_failure':      {'modal': 'blood', 'action': 'BNP/NT-proBNP 검사',     'description': '심부전 의심 — 심장 바이오마커 확인 필요'},
    'hf_detail':          {'modal': 'blood', 'action': 'BNP/NT-proBNP 검사',     'description': '심부전 의심 — 심장 바이오마커 확인 필요'},
    'sepsis':             {'modal': 'blood', 'action': '혈액배양 + 젖산 검사',    'description': '패혈증 의심 — 감염 바이오마커 확인 필요'},
    'hyperkalemia':       {'modal': 'blood', 'action': '혈중 K+ 즉시 확인',       'description': '고칼륨혈증 의심 — 전해질 검사 긴급 시행'},
    'hypokalemia':        {'modal': 'blood', 'action': '혈중 K+ 확인',            'description': '저칼륨혈증 의심 — 전해질 검사 시행'},
    'pulmonary_embolism': {'modal': 'chest', 'action': 'CT 폐혈관조영술(CTPA)',   'description': '폐색전증 의심 — 흉부 영상 확인 필요'},
}
