apiVersion: v1
kind: Service
metadata:
  name: ecg-svc
  namespace: dr-ai
spec:
  selector:
    app: ecg-svc
  ports:
    - port: 80
      targetPort: 8000
  type: ClusterIP
# 오케스트레이터에서 호출 시:
# http://ecg-svc.dr-ai.svc.cluster.local/predict
